### ISSUE TITLE
Curious...

### ISSUE THREAD

**Issue by jfmatth** [almarklein/mypaas#14]
```
(I personally avoid AWS for ethical reasons.)
```

I avoid AWS as well, because I find them to be bullies.  But your reason intrigues me.  Can you elaborate?

**Comment by almarklein** [comment]
Haha, I think Amazon has some ethical problems in different ways. I also think it's incredibly unhealthy that one person can own such incredible amounts of money. And I do not want to add to that.

**Comment by jfmatth** [comment]
Thanks for the honest answer.

And thank you for MyPass, an interesting project.  Have you ever looked at Dokku (https://github.com/dokku/dokku)? a similar project, but aimed at a Huroku alternative.

thanks again

**Comment by almarklein** [comment]
Yes, I know about Dokku, very nice project indeed :)
