### ISSUE TITLE
TOML based configuration for deployment

### ISSUE THREAD

**Issue by hydroid7** [almarklein/mypaas#34]
Thank you for the awesome project.
While using it, I've often found helpful to be able to configure the deployment in an external deploy file.
Other providers use them also, like `netlify.toml`.

My main problem was that I was not able to push because `mypaas` pushed everything but the hardcoded ignore dirs.
The file size was too large and hence refused to push. But they are hardcoded.

Therefore I extended the client with a basic configuration file option. Since the project already uses toml files, I decided to use the same and name it `mypaas.toml`.

In the future I want to extend the configuration to all config options, like better envs (maybe interpolation), etc.
Let me know you opinion. I'm happy to make a pull request, once the feature is complete.

Feel free to take a look at my fork at https://github.com/hydroid7/mypaas

**Comment by almarklein** [comment]
> My main problem was that I was not able to push because mypaas pushed everything but the hardcoded ignore dirs.

I've solved that in some projects by creating a subdir, but I see how that may not always work (well). Some way to configure this sounds like it can make sense. Maybe using a `mypaas.toml` in the directory that you're pushing?

**Comment by hydroid7** [comment]
Hi, 
yes, I've implemented this with `mypaas.toml`.
Put the following content into you root dir:
```toml
ignore = ["public", "node_modules"]
```
and it will skip these directories during deployment. 

If you find this useful, I can make a pull request.

**Comment by almarklein** [comment]
Yes, a PR would be appreciated!

**Comment by hydroid7** [comment]
@almarklein PR is opened.

**Comment by almarklein** [comment]
Thanks for the heads up. This has slipped my attention. Done in #35!
