### ISSUE TITLE
Exposing other protocols (MQTT, NATS, Websocket) to the internet

### ISSUE THREAD

**Issue by hydroid7** [almarklein/mypaas#39]
Hi there,

currently I'm looking for a way to expose a message broker to the internet.
I'm looking for MQTT and NATS. Do you have any ideas how to solve that?

Thank you in advance! :)

**Comment by almarklein** [comment]
I *think* websockets should work. I don't know anything about MQTT and NATS, but if they're build ontop of http they should work. If they're based on TCP, then I think some configuration of Traefik may be needed. Other that that, I can't be of much help :)

**Comment by hydroid7** [comment]
Hi @almarklein ,
Thanks for the response. In fact, websockets are working great.

I solved my issue with websockets, so I'm closing this issue now.
